[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  targetPort = 5173
  port = 8888
  framework = "#custom"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcryptjs", "jsonwebtoken"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"